version: '3'
services:
  app:
    container_name: exclusion-service
    image: exclusion-service:1.0-SNAPSHOT
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
  redis:
    container_name: redis-datastore
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
